server:
  port: xx
  context-path: /
  session:
    timeout: 28800

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://xx:3306/xx?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: xx
    password: xx
  output:
    ansi:
    enabled: always
  thymeleaf:
    cache: true
    content-type: text/html
    enabled: true
    prefix: classpath:/resources/
    suffix: html
    mode: LEGACYHTML5
  http:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  session:
    store-type: none

security:
  basic:
    enabled: false

com:
  laf:
    manager:
      browser:
        loginPage: /login.html
        loginType: REDIRECT
    upload:
      file:
        path: /var/lib/tomcat8/webapps/upload/images
        base: /upload/images/
        domain: http://xx:xx
    settings:
      appid: xx
      excel: export.xls
    ajax:
      url:
        api: http://xx:xx/
        manager: http://xx:xx/
    wechat:
      domain: http://xx/
      path: activity_sign_in

logging:
  level:
    org.springframework.jdbc.core.StatementCreatorUtils: debug
    org.springframework.jdbc.core: debug
  pattern:
    console: "%d - %msg%n"
  path: /var/log/springboot/
