server:
  port: xx
  context-path: /

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/member_test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: xx
    password: xx
  output:
    ansi:
      enabled: always
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  redis:
    database: 0
    host: localhost
    password:
    port: 6379
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 0
  session:
    store-type: none

security:
  basic:
    enabled: false

com:
  laf:
    manager:
      browser:
        loginPage: /login.html
        loginType: REDIRECT
    mall:
      sms:
        url: http://xx:xx/service/xx/xx.do
        username: xx
        password: xxx
        veryCode: xx
        tempid: xx-xx
    upload:
      file:
#        path: /Users/apple/Desktop
#        base: /upload/images/
#        domain: 127.0.0.1:8080
        path: /Users/apple/bbb/member/manager-app/src/main/resources/resources/upload/img
        base: /
        domain: http://localhost:xx/upload/img
    coupon:
      relate:
        isrelated: true
        couponid: 1

logging:
  level:
    org.springframework.jdbc.core.StatementCreatorUtils: debug
    org.springframework.jdbc.core: debug
#    java.sql.Connection: trace
#    java.sql.Statement: trace
#    java.sql.PreparedStatement: trace
#    java.sql.ResultSet: trace
#    org.springframework.jdbc.core: trace
#    com.laf.mall.api.repository: trace

#mybatis:
#  mapper-locations: classpath:mapper/*.xml


